In [20]:
import numpy as np
import pandas as pd

In [37]:
data = pd.read_csv("left.csv")
data.to_csv('left1.csv', header = False)
data = pd.read_csv("left1.csv")

In [45]:
data1 = pd.read_csv("right.csv")
data1.to_csv('right1.csv', header = False)
data1 = pd.read_csv("right1.csv")

In [46]:
data1.head()

Timestamp  EEG.Counter  EEG.Interpolated      EEG.AF3       EEG.F7  \
0  1.638428e+09         85.0               0.0  4218.717773  4304.743652   
1  1.638428e+09         86.0               0.0  4223.461426  4318.205078   
2  1.638428e+09         87.0               0.0  4228.846191  4323.589844   
3  1.638428e+09         88.0               0.0  4220.384766  4309.230957   
4  1.638428e+09         89.0               0.0  4205.128418  4300.897461   

        EEG.F3      EEG.FC5       EEG.T7       EEG.P7       EEG.O1  ...  \
0  4117.692383  4174.487305  4272.436035  4294.487305  4284.871582  ...   
1  4125.384766  4169.743652  4271.282227  4292.563965  4292.563965  ...   
2  4137.948730  4180.128418  4275.256348  4302.692383  4309.358887  ...   
3  4125.384766  4187.179688  4281.666504  4304.230957  4304.358887  ...   
4  4101.153809  4162.307617  4272.948730  4287.692383  4283.205078  ...   

   EQ.T7  EQ.P7  EQ.O1  EQ.O2  EQ.P8  EQ.T8  EQ.FC6  EQ.F4  EQ.F8  EQ.AF4  
0    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN     NaN  
1    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN     NaN  
2    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN     NaN  
3    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN     NaN  
4    NaN    NaN    NaN    NaN    NaN    NaN     NaN    NaN    NaN     NaN  

[5 rows x 55 columns]

In [23]:
channels = ['EEG.AF3','EEG.F7','EEG.F3','EEG.FC5','EEG.T7','EEG.P7','EEG.O1','EEG.O2','EEG.P8','EEG.T8','EEG.FC6','EEG.F4','EEG.F8','EEG.AF4']

In [47]:
XLeftdash = data[channels].to_numpy()
XRightdash = data1[channels].to_numpy()

In [50]:
XRightdash.shape

(649, 14)

In [51]:
XLeft = np.transpose(XLeftdash)
XRight = np.transpose(XRightdash)

In [52]:
XLeft.shape

(14, 649)

In [32]:
product = np.matmul(X,Xdash)

In [35]:
product

array([[1.13515990e+10, 1.16208133e+10, 1.10554232e+10, 1.12038373e+10,
        1.15359532e+10, 1.16319869e+10, 1.16271959e+10, 1.17994749e+10,
        1.17345400e+10, 1.15028132e+10, 1.19457995e+10, 1.15455426e+10,
        1.19958788e+10, 1.18772744e+10],
       [1.16208133e+10, 1.18964515e+10, 1.13176148e+10, 1.14695579e+10,
        1.18095560e+10, 1.19078652e+10, 1.19029651e+10, 1.20793234e+10,
        1.20128484e+10, 1.17756138e+10, 1.22291144e+10, 1.18193519e+10,
        1.22803875e+10, 1.21589690e+10],
       [1.10554232e+10, 1.13176148e+10, 1.07670225e+10, 1.09115302e+10,
        1.12349674e+10, 1.13284992e+10, 1.13238584e+10, 1.14916495e+10,
        1.14283995e+10, 1.12027066e+10, 1.16341511e+10, 1.12443606e+10,
        1.16829087e+10, 1.15673881e+10],
       [1.12038373e+10, 1.14695579e+10, 1.09115302e+10, 1.10580309e+10,
        1.13858002e+10, 1.14805830e+10, 1.14758619e+10, 1.16458955e+10,
        1.15818010e+10, 1.13530832e+10, 1.17903138e+10, 1.13952744e+10,
        1.183

In [53]:
np.linspace(0, data['EEG.AF3'].size, 6, dtype=int)

array([  0, 129, 259, 389, 519, 649])

In [57]:
for i in range(5):
    print(i)

0
1
2
3
4


In [78]:
indices = np.linspace(0, data['EEG.AF3'].size, 5+1, dtype=int)
sum1 = np.zeros(14)
sum2 = np.zeros(14)
for i in range(5):
    XLeftdash = data[channels].iloc[indices[i] : indices[i+1]].to_numpy()
    XRightdash = data1[channels].iloc[indices[i] : indices[i+1]].to_numpy()
    XLeft = np.transpose(XLeftdash)
    XRight = np.transpose(XRightdash)
    product_left = np.matmul(XLeft,XLeftdash)
    product_right = np.matmul(XRight,XRightdash)
    R_left = product_left / np.trace(product_left)
    R_right = product_right / np.trace(product_right)
    sum1 = np.add(sum1,R_left)
    sum2 = np.add(sum2,R_right)
R_left_avg = sum1/5
R_right_avg = sum2/5

In [83]:
sum1

array([[0.34066442, 0.34930957, 0.33213011, 0.33687682, 0.34680975,
        0.3498146 , 0.34911414, 0.35506438, 0.35306341, 0.34591038,
        0.35887207, 0.34681745, 0.36065778, 0.35689597],
       [0.34930957, 0.35817977, 0.34055832, 0.34543036, 0.35561298,
        0.35869299, 0.35797534, 0.36407438, 0.36202212, 0.3546881 ,
        0.36797887, 0.35561688, 0.36981108, 0.36595365],
       [0.33213011, 0.34055832, 0.32381309, 0.32843816, 0.33812116,
        0.34105119, 0.34036959, 0.34617054, 0.34421919, 0.33724527,
        0.34988263, 0.33813249, 0.35162288, 0.34795469],
       [0.33687682, 0.34543036, 0.32843816, 0.33313734, 0.3429561 ,
        0.34592595, 0.34523476, 0.35111508, 0.34913605, 0.34206315,
        0.35488065, 0.34296038, 0.35664753, 0.35292793],
       [0.34680975, 0.35561298, 0.33812116, 0.3429561 , 0.35306968,
        0.35612803, 0.35541449, 0.36147038, 0.35943302, 0.35215079,
        0.36534491, 0.35307161, 0.3671628 , 0.36333609],
       [0.3498146 , 0.35869299, 0.3

In [84]:
R_left_avg

array([[0.06813288, 0.06986191, 0.06642602, 0.06737536, 0.06936195,
        0.06996292, 0.06982283, 0.07101288, 0.07061268, 0.06918208,
        0.07177441, 0.06936349, 0.07213156, 0.07137919],
       [0.06986191, 0.07163595, 0.06811166, 0.06908607, 0.0711226 ,
        0.0717386 , 0.07159507, 0.07281488, 0.07240442, 0.07093762,
        0.07359577, 0.07112338, 0.07396222, 0.07319073],
       [0.06642602, 0.06811166, 0.06476262, 0.06568763, 0.06762423,
        0.06821024, 0.06807392, 0.06923411, 0.06884384, 0.06744905,
        0.06997653, 0.0676265 , 0.07032458, 0.06959094],
       [0.06737536, 0.06908607, 0.06568763, 0.06662747, 0.06859122,
        0.06918519, 0.06904695, 0.07022302, 0.06982721, 0.06841263,
        0.07097613, 0.06859208, 0.07132951, 0.07058559],
       [0.06936195, 0.0711226 , 0.06762423, 0.06859122, 0.07061394,
        0.07122561, 0.0710829 , 0.07229408, 0.0718866 , 0.07043016,
        0.07306898, 0.07061432, 0.07343256, 0.07266722],
       [0.06996292, 0.0717386 , 0.0

In [82]:
np.identity(14)/5

array([[0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. ,
        0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 